### ISSUE TITLE
Add GitHub Topics to repositories

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/lesson-infrastructure#8]
Related with https://github.com/swcarpentry/styles/pull/226.

**Comment by fmichonneau** [comment]
Coming up with good and consistent [topics](https://blog.github.com/2017-01-31-introducing-topics/) for our repositories is also potentially related to this.

**Comment by fmichonneau** [comment]
Members of the lesson infrastructure subcommittee have agreed to solicit input from the community to come up with guidelines and recommendations for keywords to use in our lessons and as GitHub topics.

I'll follow up by sending an email to the discuss mailing list: https://carpentries.topicbox.com/groups/discuss/Tf6e39c33983ade11

**Comment by katrinleinweber** [comment]
Status report: A quick, likely incomplete survey uncovers [`carpentry-lesson`](https://github.com/topics/carpentry-lesson), [`software-`](https://github.com/topics/software-carpentry) & [`data-carpentry`](https://github.com/topics/data-carpentry), [`carpentries`](https://github.com/topics/carpentries) already being in use.

**Comment by katrinleinweber** [comment]
As a minimum recommendation, please consider `carpentries-lesson`. It could be useful for _all_ lessons, because GitHub then generates a comprehensive topic page overviewing all `SWCarpentry`, `DataCarpentry`, `LibraryCarpentry` etc. repos. What do you think?

The repo names and descriptions can then be `CTRL`+`F`-searched in the browser for programming language, Carpentry, subject, etc.

**Comment by fmichonneau** [comment]
@zinnar has come up with a proposal for this, I'll put in more details before the meeting on Wednesday

**Comment by fmichonneau** [comment]
After today's committee meeting, we will implement the following for our repositories:

All repositories get: carpentries
  
They also get either:
  * carpentry-lesson
  * carpentry-infrastructure

They get: community, lesson, education where appropriate    

Carpentry community:
  - software-carpentry
  - data-carpentry
  - library-carpentry
    
Language taught:
  + R
  + Python
  + Unix
  + SQL
  + Git
  + *other languages, MATLAB, Mercurial, etc*
  
Skills taught:
  * data-cleaning
  * data-analysis
  * data-visualization
  * programming
  * version-control
  * ...
    
Language of the lesson:
  * English
  * Spanish
  * *other languages*

GitHub API documentation: https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository

**Comment by katrinleinweber** [comment]
What about forks with inofficial modificiations? Should they refrain from using the `carpentry`-specific topics? I'm asking with

- https://github.com/TIBHannover/2018-07-09-FAIR-Data-and-Software,
- https://github.com/TIBHannover/FAIR-R, and
- https://github.com/TIBHannover/git-desktop in mind.

Does `forked from...` on [a topic's page](https://github.com/topics/carpentry-lesson) indicate "inoffical" clearly enough?

**Comment by katrinleinweber** [comment]
GitLab has "tags" as well, but hidden. Maybe [Carpentries people could upvote a feature request about making them more visible](https://gitlab.com/gitlab-org/gitlab-ce/issues/2978).

**Comment by remram44** [comment]
Has this been implemented? It's probably worth somebody with appropriate permissions going over repos in swcarpentry and datacarpentry to add the `carpentry-lesson` topic, because it doesn't seem to be there.

**Comment by dpshelio** [comment]
And I've spammed everyone today :man_facepalming:  - I didn't find this because I didn't look in the right place. I didn't think to look for an issue here. Well... sorry everyone. The reason for doing this was that I went through all the lessons in dc and sc to look for rmd lessons (*i.e.*, not using jekyll). It was a manual task to check whether something was or wasn't a lesson. I found that some lessons were using `lesson` as a topic, but not the majority, so I had to go repo-by-repo and looking at the files. I would have preferred to code something and let the code do that for me... but I didn't have any obvious pattern to use.

**Comment by dpshelio** [comment]
Some have tried to solve that today and found out that maintainers couldn't add these tags. Others issues has been closed (though not solved) - e.g., datacarpentry/python-ecology-lesson#423.

**Comment by katrinleinweber** [comment]
[`lesson`](https://github.com/topics/lesson) would embed our repos with others in the wider GitHub community. +1 for that / -1 for [`carpentries-lesson`](https://github.com/carpentries/lesson-infrastructure/issues/8#issuecomment-395741230).

**Comment by fmichonneau** [comment]
This has now been submitted for comments to the Maintainers: https://github.com/carpentries/maintainer-RFCs/issues/5 Please provide feedback on the proposed topics for each lesson repository linked on that issue.

**Comment by fmichonneau** [comment]
the topics have been added to the lessons
